import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

export const metadata = {
  title: "FuelControl | Pilotage des réseaux de stations-service",
  description:
    "FuelControl est une plateforme digitale de pilotage opérationnel et financier des réseaux de stations-service.",

  keywords: [
    "FuelControl",
    "stations-service",
    "pilotage financier",
    "gestion stations",
    "supervision énergétique",
  ],

  openGraph: {
    title: "FuelControl",
    description:
      "Le contrôle et le pilotage des réseaux de stations-service",
    images: ["/og-fuelcontrol.png"],
  },
};

